import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:provider/provider.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'app.dart';
import 'core/theme/theme_notifier.dart';
import 'firebase_options.dart';
import 'database/services/chat_notification_service.dart';

@pragma('vm:entry-point')
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

Future<void> main() async {
  // Required before calling any Firebase/Supabase APIs.
  WidgetsFlutterBinding.ensureInitialized();

  // firebase_options.dart is auto-generated by running
  // `flutterfire configure` inside the frontend/ folder — see README
  // for setup steps. This will fail to compile until that's been run.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);

  await Supabase.initialize(
    url: 'https://nmzymvqwprftnviulrtg.supabase.co',

    publishableKey: 'sb_publishable_8ysjammqYxk5vGK5J0UTiA_2PVPMe5O',

    /// This is the critical Firebase -> Supabase bridge.
    accessToken: () async {
      final firebaseUser = FirebaseAuth.instance.currentUser;

      if (firebaseUser == null) {
        return null;
      }

      return await firebaseUser.getIdToken();
    },
  );

  // Load persisted theme before building the widget tree.
  final themeNotifier = await ThemeNotifier.create();

  await ChatNotificationService.instance.initialize();

  runApp(
    ChangeNotifierProvider<ThemeNotifier>.value(
      value: themeNotifier,
      child: const ResQApp(),
    ),
  );
}
